### ISSUE TITLE
Light theme better color combination

### ISSUE THREAD

**Issue by anasvakyathodi** [FOSS-Cell-GECPKD/DevPad#2]
[Material UI Theme Update](https://github.com/FOSS-Cell-GECPKD/DevPad/tree/main/blog/src/Theme)

**Comment by iampankajgupta** [comment]
what is the issue ???

**Comment by anasvakyathodi** [comment]
> what is the issue ???

Need better color theme for dark and light mode

**Comment by abba-m** [comment]
Why dont you check out [Coolor](coolor.co) for a good color palette.

**Comment by anandbaburajan** [comment]
@anasvakyathodi Did #4 fix this issue? If so, you can close this issue.
