### ISSUE TITLE
MUI Login & SignUp Page

### ISSUE THREAD

**Issue by anasvakyathodi** [FOSS-Cell-GECPKD/DevPad#6]
Create Login & Sign Up Page
1.User can enter into page without login
2.If he want to create a post, on new post page - check if he is already logged or not, if not - redirect him to login page and after login redirect back to new post page
  - If he is new, give a "register" link in the form, which will redirect to register page, after registration goto login page
3. login & register page have fields "username" and "password" and also forget password link which redirects to mail with subject "forgot password"
4. both register and login "post" request has a body {username:"",password:""} which will be passed to jwt auth on backend

**Comment by 2802harsh** [comment]
I would like to work on this. Please assign this to me

**Comment by anasvakyathodi** [comment]
> 
> 
> I would like to work on this. Please assign this to me

Sure dude. Here you go 🔥

**Comment by 2802harsh** [comment]
@anasvakyathodi Please review the PR [here](https://github.com/FOSS-Cell-GECPKD/DevPad/pull/11)

**Comment by anasvakyathodi** [comment]
> @anasvakyathodi Please review the PR [here](https://github.com/FOSS-Cell-GECPKD/DevPad/pull/11)

Pleasure to have your contribution :)
Keep contributing !
