### ISSUE TITLE
Add Local variable

### ISSUE THREAD

**Issue by anasvakyathodi** [FOSS-Cell-GECPKD/DevPad#8]
Add a local variable in the main page to know whether the user is new or not. If he is new to page, show welcome note, else hide.

![Screenshot_Dev_Pad](https://user-images.githubusercontent.com/44634141/95567744-fdf7eb00-0a40-11eb-9ffd-240976224dcf.jpg)

**Comment by jsflor** [comment]
I can handle this

**Comment by anasvakyathodi** [comment]
> 
> 
> I can handle this

Ok buddy... Go on
